# Git pre commit hooks! More supported ones here https://pre-commit.com/hooks.html
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    - id: black
      language_version: python3.9
      # You may want to add an exclude: your/repo/here|your/other/repo/here as needed
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
      # Exclusions not read from flake8 config (common flake8 hook bug) so you may want to add
      # exclude: your/repo/here|your/other/repo/here as needed
